### ISSUE TITLE
Fetch не работает в докере

### ISSUE THREAD

**Issue by zaralX** [m1handr/spworlds#2]
Сделай пожалуйста запросы через axios вот тут
https://github.com/m1handr/spworlds/blob/3489d20a29a83dff1b6c0183891f8d196e345bb6/src/index.ts#L17

Чтобы не приходилось делать костыль в каждом проекте в виде
```js
global.feth = req('fetch')
```

## Пояснение
В docker обычно используют урезанный nodejs в котором нет Fetch

**Comment by m1handr** [comment]
Перестань использовать EOL версию ноды ;)

**Comment by zaralX** [comment]
Посмотрел в какой версии появился Fetch, да тупанул, у меня был alpine node 16 а Fetch появился в 18
